<script>
  import '../app.css';
</script>
<svelte:head>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet" />
</svelte:head>


<slot />

<style>
  body {
  background-image: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MDAgNzAwIiB3aWR0aD0iNzAwIiBoZWlnaHQ9IjcwMCIgaWQ9Im5ubm9pc2UiPjxkZWZzPjxmaWx0ZXIgaWQ9Im5ubm9pc2UtZmlsdGVyIiB4PSItMjAlIiB5PSItMjAlIiB3aWR0aD0iMTQwJSIgSGVpZ2h0PSIxNDBJSIiIGZpbGVJdC1zZWFyY2gtcGFyYWxsZWxsaWMtY2hhcmFjdGVyLCJyZWdpc3RlciI+PHZkIiB0eXBlPSJmcmFjdGFsTm9pc2UiIGJhc2VGcmVxdWVuY3k9IjAuMTAyIiBub21PY3RhdmVzPSI0IiBzZWVkPSIxNSIgU3RpdGNoVGl0bGVzPSJzdG9ya3AiIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiByZXN1bHQ9InR1cnJibGVuY2UiLz48ZmVTcGVjdWxhckxpd2h0IGdyYWRpZW50LWZyb20iMzMiIHNwZWN1bGFyQ29uc3RhbnQ9IjAuNzUiIHNwZWN1bGFyRXhwb3NlbnQ9IjIwIiBsaWdodGluZy1jb2xvcj0iIzc2NTJEMCIgeHMiIG9wYWNpdHktY2hhcmFjdGVyPSJjb3JhbWVsbmE2IHRhcnJrIiB4TWF4U2xpZ2h0PSIwIiB4TWV0YS1OYW1lPSJtaW5lciIgIkFzc2V0IiAvPjwvZGVmcz48cmVjdCB3aWR0aD0iNzAwIiBoZWlnaHQ9IjcwMCIgZmlsbD0iI2M2ODYyNUQiIGZpbGw9IiNmNzc3NzciIGZpbHRlcj0idXJsKCFubm9pc2UtZmlsdGVyKSIvPjwvZ3BvcyBvbmFtcGFnZSI+');
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
}

</style>
